server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54320/pabi
    username: root
    password: pabi-be
  jpa:
    hibernate:
      ddl-auto: update