server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54320/pabi
    username: root
    password: pabi-be

  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
  access-token-validity-in-seconds: 7200
  refresh-token-validity-in-seconds: 1209600